### ISSUE TITLE
Does it work for weather / daytime style transfer?

### ISSUE THREAD

**Issue by JJack27** [YingnanMa/RAST#3]
I.e. sunny to rainy, morning to night, etc.

**Comment by YingnanMa** [comment]
if training data involves these cases, these specific transfer can achieve better performance

**Comment by YingnanMa** [comment]
> I.e. sunny to rainy, morning to night, etc.
if training data involves these cases, these specific transfer can achieve better performance

**Comment by JJack27** [comment]
> > I.e. sunny to rainy, morning to night, etc.
> > if training data involves these cases, these specific transfer can achieve better performance

马哥牛逼
